Repository livarter/android, pull requests merged in 2024-01, with the labels that each got.

#3 feat: 장바구니roomdatabase 구현, 부트페이 결제 연동
  app/build.gradle
  app/src/main/java/net/developia/livartc/PurchaseActivity.kt
  app/src/main/java/net/developia/livartc/adapter/CartRecyclerViewAdapter.kt
  app/src/main/java/net/developia/livartc/db/AppDatabase.kt
  app/src/main/java/net/developia/livartc/db/CartDao.kt
  app/src/main/java/net/developia/livartc/db/CartEntity.kt
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailAddToCartFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsResultFragment.kt
  app/src/main/res/drawable/product_sample.png
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_bills_result.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_add_to_cart.xml
  app/src/main/res/layout/item_cart.xml
  mylibrary/src/main/AndroidManifest.xml
Labels: feature

#4 feat: api.properties 생성
  app/build.gradle
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
Labels: feature

#5 feat: 장바구니, 주문서 세부 UI 변경
  app/src/main/java/net/developia/livartc/PurchaseActivity.kt
  app/src/main/java/net/developia/livartc/adapter/CartRecyclerViewAdapter.kt
  app/src/main/java/net/developia/livartc/db/CartDao.kt
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailAddToCartFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/res/layout/activity_purchase.xml
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_cart.xml
Labels: enhancement

#11 주문내역 API 연동
  app/src/main/java/net/developia/livartc/model/PurchaseReqDto.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/retrofit/INetworkService.kt
Labels: feature

#16 feat: 검색버튼 추가했습니다.
  .gitignore
  app/src/main/java/net/developia/livartc/MainActivity.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/menu/menu_bottom_nav.xml
Labels: feature

#18 Fix: HomeFragment 오류 수정
  .gitignore
  app/src/main/java/net/developia/livartc/MainActivity.kt
  app/src/main/java/net/developia/livartc/ProductActivity.kt
  app/src/main/java/net/developia/livartc/ReplyWriteActivity.kt
  app/src/main/java/net/developia/livartc/adapter/BestProductAdapter.kt
  app/src/main/java/net/developia/livartc/main/HomeFragment.kt
  app/src/main/java/net/developia/livartc/model/User.kt
  app/src/main/java/net/developia/livartc/product/DetailFragment.kt
  app/src/main/java/net/developia/livartc/product/SearchFragment.kt
  app/src/main/java/net/developia/livartc/retrofit/INetworkService.kt
  app/src/main/java/net/developia/livartc/spring하는법
  app/src/main/res/drawable/cat.jpg
  app/src/main/res/layout/activity_reply_write.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_review.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/config.xml
Labels: bug, feature

#20 Delete config.xml
  app/src/main/res/values/config.xml
Labels: enhancement

#19 장바구니 기능 수정
  app/src/main/java/net/developia/livartc/MainActivity.kt
  app/src/main/java/net/developia/livartc/PurchaseActivity.kt
  app/src/main/java/net/developia/livartc/adapter/CartRecyclerViewAdapter.kt
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailAddToCartFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsResultFragment.kt
  app/src/main/res/layout/fragment_bills_result.xml
  app/src/main/res/layout/fragment_cart.xml
Labels: bug, feature

#23 Feat: MainActivity의 뒤로가기로직 및 카테고리 버튼 수정
  app/src/main/java/net/developia/livartc/MainActivity.kt
  app/src/main/java/net/developia/livartc/main/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: bug, feature

#24 주문목록 조회 & 장바구니 비어있을 때 버튼 연결
  app/src/main/java/net/developia/livartc/adapter/PurchaseAdapter.kt
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/main/MyPageFragment.kt
  app/src/main/java/net/developia/livartc/main/MyPurchaseFragment.kt
  app/src/main/java/net/developia/livartc/model/PurchaseHistory.kt
  app/src/main/java/net/developia/livartc/retrofit/INetworkService.kt
  app/src/main/res/layout/fragment_my_purchase.xml
  app/src/main/res/layout/item_purchase.xml
Labels: feature

#25 Feature/fix login 로그인 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/developia/livartc/LoginActivity.kt
Labels: bug

#26 Feature/fix 주문서 및 장바구니 UI 수정 및 기능 수정
  app/src/main/java/net/developia/livartc/PurchaseActivity.kt
  app/src/main/java/net/developia/livartc/adapter/CartRecyclerViewAdapter.kt
  app/src/main/java/net/developia/livartc/adapter/PurchaseAdapter.kt
  app/src/main/java/net/developia/livartc/db/CartEntity.kt
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/main/MyPurchaseFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailAddToCartFragment.kt
  app/src/main/java/net/developia/livartc/product/DetailFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsResultFragment.kt
  app/src/main/java/net/developia/livartc/retrofit/INetworkService.kt
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_detail_add_to_cart.xml
Labels: enhancement

#28 Search 페이지 구현, pl/sql sorting option 적용 오류
  .gitignore
  app/src/main/java/net/developia/livartc/adapter/BrandAdapter.kt
  app/src/main/java/net/developia/livartc/adapter/HashTagAdapter.kt
  app/src/main/java/net/developia/livartc/product/SearchFragment.kt
  app/src/main/res/layout/fragment_search_sortingdropdown.xml
Labels: bug, feature

#31 feat: picasso 의존성 추가
  app/build.gradle
Labels: bug

#36 feat: 폰트 크기 dimens.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#37 Feature/fix myinfo 뱃지 및 쿠폰 탭 클릭 시 NPE 해결
  app/src/main/java/net/developia/livartc/mypage/badge/BadgeFragment.kt
  app/src/main/java/net/developia/livartc/mypage/badge/GridAdapter.kt
  app/src/main/java/net/developia/livartc/mypage/badge/GridItem.kt
  app/src/main/java/net/developia/livartc/mypage/dto/Badge.kt
  app/src/main/java/net/developia/livartc/mypage/dto/Chronology.kt
  app/src/main/java/net/developia/livartc/mypage/dto/CouponDeatilResDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/CouponListResDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/CouponResDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/CreatedAt.kt
  app/src/main/java/net/developia/livartc/mypage/dto/MemberGradeDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/MemberResDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/MemperUpdateReqDto.kt
  app/src/main/java/net/developia/livartc/mypage/dto/UpdatedAt.kt
Labels: bug

#39 feat: 폰트 크기 일괄 수정
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_bills_result.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_detail_add_to_cart.xml
  app/src/main/res/layout/fragment_point_apply.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_purchase.xml
Labels: enhancement

#43 feat: 포인트/배송비 조회 및 적용 결제 && 포인트 삭제/적립 && 주문내역 조회 && 헤더 설정
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/main/MyPageFragment.kt
  app/src/main/java/net/developia/livartc/main/MyPurchaseFragment.kt
  app/src/main/java/net/developia/livartc/mypage/membership/MyOrderActivity.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsResultFragment.kt
  app/src/main/java/net/developia/livartc/purchase/PointApplyFragment.kt
  app/src/main/java/net/developia/livartc/retrofit/INetworkService.kt
  app/src/main/res/layout/activity_my_order.xml
  app/src/main/res/layout/activity_purchase.xml
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_bills_result.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_my_purchase.xml
  app/src/main/res/layout/fragment_point_apply.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_purchase.xml
Labels: feature

#44 fix: coupon 제거 & 상품 검색 페이지 배경색 추가
  app/src/main/java/net/developia/livartc/purchase/PointApplyFragment.kt
  app/src/main/res/layout/activity_product.xml
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_point_apply.xml
Labels: bug

#49 fix: loginloading & Toast
  app/src/main/java/net/developia/livartc/LoginActivity.kt
  app/src/main/java/net/developia/livartc/product/DetailAddToCartFragment.kt
  app/src/main/java/net/developia/livartc/purchase/PointApplyFragment.kt
  app/src/main/res/drawable/toast_shape.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/toast_board.xml
Labels: enhancement

#52 feat: click effect 부여 및 헤더 통일
  app/src/main/java/net/developia/livartc/product/SearchFragment.kt
  app/src/main/res/drawable/click_effect.xml
  app/src/main/res/layout/activity_my_order.xml
  app/src/main/res/layout/activity_purchase.xml
  app/src/main/res/layout/activity_reply_write.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_add_to_cart.xml
  app/src/main/res/layout/fragment_filtered_product.xml
  app/src/main/res/layout/fragment_header.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_membership.xml
  app/src/main/res/layout/fragment_search_items.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_purchase.xml
Labels: feature

#56 추가 기능 구현 - brand, category 검색 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/net/developia/livartc/MainActivity.kt
  app/src/main/java/net/developia/livartc/ProductActivity.kt
  app/src/main/java/net/developia/livartc/adapter/ProductAdapter.kt
  app/src/main/java/net/developia/livartc/main/CollectionsFragment.kt
  app/src/main/java/net/developia/livartc/main/HomeFragment.kt
  app/src/main/java/net/developia/livartc/product/BrandCategoryFragment.kt
  app/src/main/res/drawable/brand_artu.png
  app/src/main/res/drawable/brand_billiani.png
  app/src/main/res/drawable/brand_copiosa.png
  app/src/main/res/drawable/brand_ethnicraft.png
  app/src/main/res/drawable/brand_fogia.png
  app/src/main/res/drawable/brand_levart.png
  app/src/main/res/drawable/brand_magis.png
  app/src/main/res/drawable/brand_miniforms.png
  app/src/main/res/drawable/brand_mogg.png
  app/src/main/res/drawable/brand_moustache.png
  app/src/main/res/drawable/brand_toneli.png
  app/src/main/res/drawable/inner_artu.jpeg
  app/src/main/res/drawable/inner_billiani.jpeg
  app/src/main/res/drawable/inner_copiosa.jpeg
  app/src/main/res/drawable/inner_ethnicraft.jpeg
  app/src/main/res/drawable/inner_levart.jpeg
  app/src/main/res/drawable/inner_miniforms.jpeg
  app/src/main/res/drawable/inner_mogg.jpeg
  app/src/main/res/drawable/inner_moustache.png
  app/src/main/res/drawable/inner_tonelli.jpeg
  app/src/main/res/layout/fragment_brand_category_page.xml
  app/src/main/res/layout/fragment_collections.xml
  app/src/main/res/layout/fragment_membership.xml
  app/src/main/res/layout/fragment_search_brandhashtag.xml
  app/src/main/res/layout/fragment_search_items.xml
  app/src/main/res/layout/fragment_search_searchbar.xml
  app/src/main/res/layout/fragment_search_sortingdropdown.xml
  app/src/main/res/values/brand_description.xml
  app/src/main/res/values/brand_strings.xml
Labels: bug, feature

#58 fix: bills phone & 이동 버튼 연결 & 버튼 click_effect
  app/src/main/java/net/developia/livartc/main/CartFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsFragment.kt
  app/src/main/java/net/developia/livartc/purchase/BillsResultFragment.kt
  app/src/main/res/layout/fragment_bills.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/fragment_detail_add_to_cart.xml
Labels: enhancement

#61 fix: price format
  app/src/main/java/net/developia/livartc/adapter/BestProductAdapter.kt
  app/src/main/java/net/developia/livartc/product/DetailFragment.kt
Labels: bug
